CrowdsourcedDataAnnotationPlatform/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('UserManagement/', include('UserManagement.urls', namespace='UserManagement')),
    #path('UserManagement/',include('password_reset.urls')),
    path('', views.home, name='home'),
    path('UserManagement/', include('django.contrib.auth.urls')),
    path('DoDataAnnotationTask/', include('DoDataAnnotationTask.urls')),
    path('DoDataGenerationTask/', include('DoDataGenerationTask.urls')),
    path('DoTextDataAnnotationTask/', include('DoTextDataAnnotationTask.urls')),
    path('CreateTextDataAnnotationTask/', include('CreateTextDataAnnotationTask.urls')),
    path('DoTask/', include('DoTask.urls')),
    path('task/', include('CreateTask.urls')),
    path('TextDataAnalyse/', include('TextDataAnalyse.urls')),
    path('ImageDataAnalyse/', include('ImageDataAnalyse.urls')),
    path('ResultAnalyse/', include('testresultrank.urls')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

DoTask/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #path('', views.first),
    path('test', views.test),
    path('Task', views.task),
    path('ViewMyContributions',views.view_my_contributions),
    path('ViewMyContributions/Change', views.view_my_contributions_change),
    path('SkipDataInstance', views.skip_data_instance),
    path('StopContributing', views.stop_contributing),
    #path('ViewMyAnnotations/Delete', views.view_my_annotations_delete),
]

UserManagement/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from .forms import ResetPasswordForm
from django.conf.urls import url

app_name = 'UserManagement'

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/change_password/', views.change_password, name='change_password'),
    path ('search/', views.search, name='search'),
    #path ('rate/', views.rate, name='rate'),

    path ('profile_list/', views.profiles, name='profile_list'),
    path ('profile_list/view_profile/<str:pk>', views.view_profile, name='view_profile'),
    path ('profile_list/delete_profile/<str:pk>',views.delete_profile, name="delete_profile"),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='UserManagement/reset_password.html',
                                                                form_class=ResetPasswordForm), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='UserManagement/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='UserManagement/password_reset_complete.html'), name='password_reset_complete'),
    
    path('MyTasks/', views.view_my_tasks , name = 'MyTasks'),
    path('field_task_list/', views.view_field_task_list, name='field_task_list'),
    path('author_task_list/', views.view_author_task, name='author_task_list'),
    path ('author_task_list/delete_task/<str:pk>',views.delete_task, name="delete_task"),

    path ('task_contributors/<str:pk>', views.view_task_contributors, name='view_task_contributors'),
    path('Reg_task/<str:pk>', views.reg_task, name='reg_task'),
    path('review/<str:pk>', views.review, name='review'),

    #path('Reg_task/<str:pk>', views.reg_task, name='reg_task'),
    url(r'^return_contributor_task_list/$',views.view_field_task_list, name='return_field_task_list')


]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

UserManagement/models.py
from CreateTask.models import Task
#from tkinter import Image

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True, default='avatars/no-image.png')
    first_name = models.CharField(max_length=255, default='')
    last_name = models.CharField(max_length=255, default='', null=True)
    email = models.EmailField(default='none@email.com')
    bio = models.TextField(default='')
    is_contributor = models.BooleanField(default=False)
    is_author = models.BooleanField(default=False)
    country = models.CharField(max_length=255, default='')
    field = models.CharField(max_length=255, default='')


    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        profile = Profile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

class ContributorTask(models.Model):
    Task = models.ForeignKey(Task, on_delete=models.CASCADE)
    User = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('Task', 'User'),)

class Review (models.Model):
    user = models.ForeignKey(User, unique=True, on_delete=models.CASCADE)
    is_good = models.IntegerField(default=0)

UserManagement/views.py
from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout, update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm, PasswordChangeForm)
from django.contrib.auth.models import Group, User
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from . import models
from .forms import *
from .filters import ProfileFilter
from .forms import ProfileForm  # RateForm
from .models import Profile, ContributorTask, Review
from django.contrib import messages
from CreateTask.models import Task,TestResult,AnnotationTest
from .decorators import unauthenticated_user, allowed_user


def sign_in(request):
    if request.user.is_authenticated:
        messages.success(request, 'Please sign out first to sign in with different account')
        return redirect('home')
    else:
        form = SigInForm()
        username = 'not logged in'
        if request.method == 'POST':
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                if form.user_cache is not None:
                    user = form.user_cache
                    username = form.cleaned_data['username']
                    request.session['user_id'] = user.id
                    if user.is_active:
                        login(request, user)
                        return HttpResponseRedirect(
                            reverse('home')  # TODO: go to profile
                        )
                    else:
                        messages.error(
                            request,
                            "That user account has been disabled."
                        )
                else:
                    messages.error(
                        request,
                        "Username or password is incorrect."
                    )
        return render(request, 'UserManagement/sign_in.html', {'form': form})


def formView(request):
    if request.session.has_key('username'):
        username = request.session['username']
        return render(request, 'profile.html', {"username": username})
    else:
        return render(request, 'sign_in.html', {})


def sign_up(request):
    if request.user.is_authenticated:
        messages.success(request, 'Please sign out first to sign up with different account')
        return redirect('home')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            review = Review()
            form = CreateUserForm(data=request.POST)
            if form.is_valid():
                new_user = form.save()
                user = authenticate(
                    username=form.cleaned_data['username'],
                    password=form.cleaned_data['password1']
                )
                group = Group.objects.get(name='crowd_user')
                new_user.groups.add(group)
                login(request, user)
                request.session['user_id'] = user.id
                review.user_id = request.session['user_id']
                review.save()
                messages.success(request, "Congradulations! Your account was created successfully")
                return HttpResponseRedirect(reverse('UserManagement:edit_profile'))  # TODO: go to profile
        return render(request, 'UserManagement/sign_up.html', {'form': form})


def sign_out(request):
    logout(request)
    try:
        del request.session['username']
    except:
        pass
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


@login_required(login_url='UserManagement:sign_in')
def profile(request):
    """Display User Profile"""
    profile = request.user.profile
    all_user_tasks = ContributorTask.objects.filter(User_id=request.session['user_id'])
    user = request.user
    all_author_tasks = Task.objects.filter(creatorID=user)
    user_text_data_generation_tasks = []
    user_image_data_generation_tasks = []
    user_text_data_annotation_tasks = []
    user_image_data_annotation_tasks = []
    for user_task in all_user_tasks:
        if user_task.Task.taskType == 'TextAnno':
            if len(user_task.Task.description) > 140:
                user_task.Task.description1 = user_task.Task.description[0:140]
                user_task.Task.description2 = user_task.Task.description[140:]
                user_text_data_annotation_tasks += [user_task.Task]
            else:
                user_text_data_annotation_tasks += [user_task.Task]
        elif user_task.Task.taskType == 'ImageAnno':
            if len(user_task.Task.description) > 140:
                user_task.Task.description1 = user_task.Task.description[0:140]
                user_task.Task.description2 = user_task.Task.description[140:]
                user_image_data_annotation_tasks += [user_task.Task]
            else:
                user_image_data_annotation_tasks += [user_task.Task]
        elif user_task.Task.taskType == 'TextGen':
            if len(user_task.Task.description) > 140:
                user_task.Task.description1 = user_task.Task.description[0:140]
                user_task.Task.description2 = user_task.Task.description[140:]
                user_text_data_generation_tasks += [user_task.Task]
            else:
                user_text_data_generation_tasks += [user_task.Task]
        elif user_task.Task.taskType == 'ImgGen':
            if len(user_task.Task.description) > 140:
                user_task.Task.description1 = user_task.Task.description[0:140]
                user_task.Task.description2 = user_task.Task.description[140:]
                user_image_data_generation_tasks += [user_task.Task]
            else:
                user_image_data_generation_tasks += [user_task.Task]
    return render(request, 'UserManagement/profile.html', {'profile': profile, 'all_author_tasks': all_author_tasks,
                                                           'user_text_data_annotation_tasks': user_text_data_annotation_tasks,
                                                           'user_image_data_annotation_tasks': user_image_data_annotation_tasks,
                                                           'user_text_data_generation_tasks': user_text_data_generation_tasks,
                                                           'user_image_data_generation_tasks': user_image_data_generation_tasks,
                                                           'user_id': request.session['user_id']})


@login_required(login_url='UserManagement:sign_in')
def edit_profile(request):
    user = request.user
    profile = get_object_or_404(models.Profile, user=user)

    form = ProfileForm(instance=profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            user.email = profile.email
            user.save()
            form.save()
            messages.success(request, "Updated the Profile Successfully!")
            return HttpResponseRedirect(reverse('UserManagement:profile'))

    return render(request, 'UserManagement/edit_profile.html', {
        'form': form
    })


@login_required(login_url='UserManagement:sign_in')
def change_password(request):
    if request.method == 'POST':
        form = PWChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return HttpResponseRedirect(reverse('UserManagement:profile'))
    else:
        form = PWChangeForm(request.user)
    return render(request, 'UserManagement/change_password.html', {
        'form': form
    })


def search(request):
    profile_list = Profile.objects.all().exclude(first_name='')
    searchFilter = ProfileFilter(request.GET, queryset=profile_list)
    return render(request, 'UserManagement/search.html', {'filter': searchFilter})


def profiles(request):
    profiles = Profile.objects.all().exclude(first_name='')
    return render(request, 'UserManagement/profile_list.html', {'profiles': profiles})


def view_profile(request, pk):
    profile = Profile.objects.get(user=pk)
    context = {'profile': profile}

    return render(request, 'UserManagement/view_profile.html', context)


@login_required(login_url='UserManagement:sign_in')
@allowed_user(allowed_roles=['admin'])
def delete_profile(request, pk):
    profile = get_object_or_404(Profile, user=pk)
    user = get_object_or_404(User, id=pk)
    context = {'profile': profile}
    if request.method == "POST":
        profile.delete()
        user.delete()
        messages.success(request, 'You have deleted a user')
        return HttpResponseRedirect(reverse('UserManagement:profile_list'))
    return render(request, 'UserManagement/delete_profile.html', context)


@login_required(login_url='UserManagement:sign_in')
def delete_task(request, pk):
    task = get_object_or_404(Task, id=pk)
    if request.method == "POST":
        task.delete()
        messages.success(request, 'You have deleted a task')
        return HttpResponseRedirect(reverse('UserManagement:author_task_list'))
    return render(request, 'UserManagement/delete_task.html', {'task': task})


"""def rate(request):
    if request.method == "POST":
        form = RateForm()
        if form.is_valid():
            rate = form.save()"""


@login_required(login_url='UserManagement:sign_in')
def view_field_task_list(request):
    user = request.session['user_id']
    profile = Profile.objects.get(user_id=user)
    user_field = profile.field
    registeredTasks = ContributorTask.objects.filter(User_id=user)
    registeredTaskID = []
    for i in registeredTasks:
        registeredTaskID += [i.Task_id]

templates/UserManagement/author_task_list.html
{% extends 'layout.html' %}
{% load static %}

{% block title %} Authored Tasks  |{% endblock %}

{% block style %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
{% endblock %}


{% block body %}

<div class="container">

    <br> <h2 class="text-center">My Authored Tasks</h2>
    <hr>
    {% if all_author_tasks %}
    <div class="row">
    {% for task in all_author_tasks %}
    <div class="col-md-4">
        <figure class="card card-product">
            {% if task.taskType == "ImageAnno" %}
            <div class="img-wrap"><img src="{% static 'img/img_type.png' %}"></div>
            {% elif task.taskType == "TextAnno" %}
            <div class="img-wrap"><img src="{% static 'img/text_folder.png' %}"></div>
            {% endif %}
            <figcaption class="info-wrap">
                    <h4 class="title">{{task.title}}</h4>
                    <p class="desc">{{task.description}}</p>
                    <div class="rating-wrap">
                        <div class="label-rating"><a href="{% url 'UserManagement:view_task_contributors' task.id %}">Contributors</a></div>
                        <div class="label-rating"><a href="/ResultAnalyse/Rank/?Task_ID={{task.id}}" class="btn btn-sm btn-outline-primary">Test result analysis </a></div>
                    </div> <!-- rating-wrap.// -->
            </figcaption>
            <div class="bottom-wrap">
                <a href="{% url 'UserManagement:delete_task' task.id %}" class="btn btn-sm btn-danger float-right">Delete</a>	
                <div class="price-wrap h5">
                    {% if task.taskType == "ImageAnno" %}
                        <a href="/ImageDataAnalyse/Analyse/?Task_ID={{task.id}}" class="btn btn-sm btn-outline-primary">Task analysis</a></button>
                    {% endif %}
                    {% if task.taskType == "TextAnno" %}
                        <a href="/TextDataAnalyse/Analyse/?Task_ID={{task.id}}" class="btn btn-sm btn-outline-primary">Task analysis</a></button>
                    {% endif %}
                </div> <!-- price-wrap.// -->
            </div> <!-- bottom-wrap.// -->
        </figure>
    </div> <!-- col // -->
    {% endfor %}
    
    </div> <!-- row.// -->
    {% else %}
    <h3>you haven't authored any tasks</h3>
    
    {% endif %}
    </div> 

{% endblock %}

templates/UserManagement/rate.html
{% extends "layout.html" %}
{% load static %}

{% block title %}Delete Task | {{ super }}{% endblock %}

{% block style %}
<link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body %}
	<main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
      <div class="card login-card">
        <div class="row no-gutters">
          <div class="col-md-5">
            <img src="{% static 'img/delete.png' %}" alt="login" class="login-card-img">
          </div>
          <div class="col-md-7">
            <div class="card-body">
              <div class="brand-wrapper">
                <!--img src="assets/images/logo.svg" alt="logo" class="logo"-->
              </div>
              <p class="login-card-description">Are you sure you want to rate {{task}}?</p>
              <p style="color:red">{{form.errors}}</p>
              <form method="POST" action="">
                {% csrf_token %}
                  <a href="{% url 'UserManagement:view_task_contributors' %}" class="btn btn-block btn-primary">NO, take me back.</a> <br> <br>
                  <input name="login" id="login" class="btn btn-block btn-danger" type="submit" value="Yes, I'm sure">
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

{% endblock %}

templates/UserManagement/search.html
{% extends 'layout.html' %}
{% load static %}
{% load auth_extras %}

<!link rel="stylesheet" href="{% static 'assets/css/circle/search.css' %}">
{% block style %}
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
{% endblock %}

{% block body %}
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>

<section id="team" class="pb-5">
    <div class="container">
        <h5 class="section-title h1">OUR TEAM</h5>
        <div class="row">
            {% if filter.qs %}
            {% for user in filter.qs %}
            <!-- Team member -->
            <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="image-flip" >
                    <div class="mainflip flip-0">
                        <div class="frontside">
                            <div class="card">
                                <div class="card-body text-center">
                                    <p><img class=" img-fluid" src="{{user.avatar.url}}" alt="card image"></p>
                                    <h4 class="card-title">{{user.first_name}} {{user.last_name}}</h4>
                                    {% if user.is_author %}
                                    <p class="card-text">Author in {{user.field}} field</p>
                                    {% endif %}
                                    {% if user.is_contributor %}
                                    <p class="card-text">Contributor in {{user.field}} field</p>
                                    {% endif %}
                                    <a href="" class="btn btn-primary btn-sm"><i class="fa fa-eye"></i></a>
                                    
                                </div>
                            </div>
                        </div>
                        <div class="backside">
                            <div class="card">
                                <div class="card-body text-center mt-4">
                                    <h4 class="card-title">{{user.first_name}} {{user.last_name}}</h4>
                                    <p class="card-text">{{user.bio}}</p>
                                    <p class="card-text"><i class="fa fa-envelope" style="padding-right: 5px;"></i>{{user.email}}</p>
                                    {% if request.user.is_authenticated %}
                                    <a href="{% url 'UserManagement:view_profile' user.id %}" ><i class="fa fa-eye"></i></a>
                                    {% endif %}
                                    {% if request.user.is_authenticated and request.user|has_group:"admin" %}
                                    <a href="{% url 'UserManagement:delete_profile' user.id %}" ><i class="fa fa-trash" style="color: red;"></i></a>
                                    {% endif %}
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <!-- ./Team member -->

        </div>
    </div>
    {% else %}
        <p>Sorry, No matches found</p>
    {% endif %}
</section>

{% endblock %}

templates/UserManagement/sign_in.html
{% extends "layout.html" %}
{% load static %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block style %}
<link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body %}
<h1 style="align-content: center;">Welcome to CDAP !!!</h1>
	<main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
      <div class="card login-card">
        <div class="row no-gutters">
          <div class="col-md-5">
            <img src="{% static 'img/login3.jpg' %}" alt="login" class="login-card-img">
          </div>
          <div class="col-md-7">
            <div class="card-body">
              <div class="brand-wrapper">
                <!--img src="assets/images/logo.svg" alt="logo" class="logo"-->
              </div>
              <p class="login-card-description">Sign into your account</p>
              <form method="POST" action="{% url 'UserManagement:sign_in' %}">
                {% csrf_token %}
                <div class="i">
           		   		<i class="fas fa-user"></i>
                </div>
                  <div class="form-group">
                    {{form.username}}
                  </div>
				  <div class="i">
           		   		<i class="fas fa-lock"></i>
                </div>
                  <div class="form-group mb-4">
                    {{form.password}}
                  </div>
                  <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit" value="Login">
                </form>
                <a href="{% url 'UserManagement:password_reset' %}" class="forgot-password-link">Forgot password?</a>
                <p class="login-card-footer-text">Don't have an account? <a href="{% url 'UserManagement:sign_up' %}" class="text-reset">Click here to sign up</a></p>
                <nav class="login-card-footer-nav">
                  <a href="#!">Terms of use.</a>
                  <a href="#!">Privacy policy</a>
                </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

{% endblock %}

templates/UserManagement/sign_up.html
{% extends "layout.html" %}
{% load static %}

{% block title %}Sign Up | {{ super }}{% endblock %}

{% block style %}
<link href="https://fonts.googleapis.com/css?family=Karla:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.8.95/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body %}
<h1 style="align-content:center">Welcome to CDAP !!!</h1>
	<main class="d-flex align-items-center min-vh-100 py-3 py-md-0">
    <div class="container">
      <div class="card login-card">
        <div class="row no-gutters">
          <div class="col-md-5">
            <img src="{% static 'img/login.jpg' %}" alt="login" class="login-card-img">
          </div>
          <div class="col-md-7">
            <div class="card-body">
              <div class="brand-wrapper">
                <!--img src="assets/images/logo.svg" alt="logo" class="logo"-->
              </div>
              <p class="login-card-description">Sign up to create your account</p>
              <p style="font_color:red">{{form.errors}}</p>
              <form method="POST" action="{% url 'UserManagement:sign_up' %}">
                {% csrf_token %}
                <div class="i">
					<i class="fas fa-user"></i>
                </div>
                  <div class="form-group">
                    {{form.username}}
                  </div>
				  <div class="i">
					<i class="fas fa-lock"></i>
                </div>
                  <div class="form-group mb-4">
                    {{form.password1}}
                  </div>
				  <div class="i">
					<i class="fas fa-lock"></i>
                </div>
                  <div class="form-group mb-4">
                    {{form.password2}}
                  </div>
                  <input name="login" id="login" class="btn btn-block login-btn mb-4" type="submit" value="Register">
                </form>
                <p class="login-card-footer-text">You have an account? <a href="{% url 'UserManagement:sign_in' %}" class="text-reset">Click here to sign in</a></p>
                <nav class="login-card-footer-nav">
                  <a href="#">Terms of use.</a>
                  <a href="#!">Privacy policy</a>
                </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

{% endblock %}

templates/UserManagement/task_contributors.html
{% extends 'layout.html' %}
{% load static %}

{% block title %} Authored Tasks  |{% endblock %}

{% block style %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
{% endblock %}


{% block body %}

<div class="container">

    <br> <h2 class="text-center">Current Contributors</h2>
    <hr>
    {% if contributor_details %}
    <div class="row">
    {% for each in contributor_details %}
    <div class="col-md-4">
        <figure class="card card-product">
            <div class="img-wrap"><img src="{{each.avatar.url}}"></div>
            <figcaption class="info-wrap">
                    <h4 class="title">{{each.first_name}} {{each.last_name}}</h4>
                    <p class="desc"></p>
                    <div class="bottom-wrap">
                <a href="{% url 'UserManagement:view_profile' each.user_id %}" class="btn btn-sm btn-outline-primary float-right">View profile</a>
                <div class="price-wrap h5">
                        <!--a href="{% url 'UserManagement:review' each.user_id %}" class="btn btn-sm btn-outline-success">Rate</a-->
                </div> <!-- price-wrap.// -->
            </div> <!-- bottom-wrap.// -->
            </figcaption>
        </figure>
    </div> <!-- col // -->
    {% endfor %}

    </div> <!-- row.// -->
    {% else %}
    <h3>No contributors have been registered !!!</h3>

    {% endif %}
    </div>

{% endblock %}