CrowdsourcedDataAnnotationPlatform/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('UserManagement/', include('UserManagement.urls', namespace='UserManagement')),
    #path('UserManagement/',include('password_reset.urls')),
    path('', views.home, name='home'),
    path('UserManagement/', include('django.contrib.auth.urls')),
    path('DoDataAnnotationTask/', include('DoDataAnnotationTask.urls')),
    path('DoDataGenerationTask/', include('DoDataGenerationTask.urls')),
    path('DoTextDataAnnotationTask/', include('DoTextDataAnnotationTask.urls')),
    path('CreateTextDataAnnotationTask/', include('CreateTextDataAnnotationTask.urls')),
    path('DoTask/', include('DoTask.urls')),
    path('task/', include('CreateTask.urls')),
    path('TextDataAnalyse/', include('TextDataAnalyse.urls')),
    path('ImageDataAnalyse/', include('ImageDataAnalyse.urls')),
    path('ResultAnalyse/', include('testresultrank.urls')),
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

DoTask/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #path('', views.first),
    path('test', views.test),
    path('Task', views.task),
    path('ViewMyContributions',views.view_my_contributions),
    path('ViewMyContributions/Change', views.view_my_contributions_change),
    path('SkipDataInstance', views.skip_data_instance),
    path('StopContributing', views.stop_contributing),
    #path('ViewMyAnnotations/Delete', views.view_my_annotations_delete),
]

UserManagement/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views
from .forms import ResetPasswordForm
from django.conf.urls import url

app_name = 'UserManagement'

urlpatterns = [
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/change_password/', views.change_password, name='change_password'),
    path ('search/', views.search, name='search'),
    #path ('rate/', views.rate, name='rate'),

    path ('profile_list/', views.profiles, name='profile_list'),
    path ('profile_list/view_profile/<str:pk>', views.view_profile, name='view_profile'),
    path ('profile_list/delete_profile/<str:pk>',views.delete_profile, name="delete_profile"),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='UserManagement/reset_password.html',
                                                                form_class=ResetPasswordForm), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='UserManagement/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='UserManagement/password_reset_complete.html'), name='password_reset_complete'),
    
    path('MyTasks/', views.view_my_tasks , name = 'MyTasks'),
    path('field_task_list/', views.view_field_task_list, name='field_task_list'),
    path('author_task_list/', views.view_author_task, name='author_task_list'),
    path ('author_task_list/delete_task/<str:pk>',views.delete_task, name="delete_task"),

    path ('task_contributors/<str:pk>', views.view_task_contributors, name='view_task_contributors'),
    path('Reg_task/<str:pk>', views.reg_task, name='reg_task'),
    path('review/<str:pk>', views.review, name='review'),

    #path('Reg_task/<str:pk>', views.reg_task, name='reg_task'),
    url(r'^return_contributor_task_list/$',views.view_field_task_list, name='return_field_task_list')


]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block style %}

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {font-family: "Lato", sans-serif}
.mySlides {display: none}
</style>
{% endblock %}



<body>
{% block body %}

{% for m in messages %}
    <p>{{m}}</p>
{% endfor %}

<!-- Page content -->
<div class="w3-content" style="max-width:2000px;margin-top:46px">

  <!-- Automatic Slideshow Images -->
  <div class="w3-display-container w3-center">
    <img src="{% static 'img/img1.jpg' %}" style="width:80%">
  </div>

  <!-- The Band Section -->
  <div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="band">
    <h2 class="w3-wide">CDAP</h2>
    <p class="w3-justify">We provide a platform to connect annotators with researchers. To annotate your data sets and to earn by annotating data sets, simply register in our site. </p>
  </div>

  <!-- The Tour Section -->
  <div class="w3-black" id="tour">
    <div class="w3-container w3-content w3-padding-64" style="max-width:800px">
      <h2 class="w3-wide w3-center">OUR SERVICES</h2>
      <div class="w3-row-padding w3-padding-32" style="margin:0 -16px">
        <div class="w3-third w3-margin-bottom">
          <img src="{% static 'img/annotation.jpeg' %}" alt="" style="width:100%" class="w3-hover-opacity">
          <div class="w3-container w3-white">
            <p><b>Data annotation</b></p>
          </div>
        </div>
        <div class="w3-third w3-margin-bottom">
          <img src="{% static 'img/generation.jpg' %}" alt="Paris" style="width:100%" class="w3-hover-opacity">
          <div class="w3-container w3-white">
            <p><b>Data Generation</b></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- End Page Content -->
</div>

<!-- Image of location/map -->
<img src="/w3images/map.jpg" class="w3-image w3-greyscale-min" style="width:100%">

<script>
// Automatic Slideshow - change image every 4 seconds
var myIndex = 0;
carousel();

function carousel() {
  var i;
  var x = document.getElementsByClassName("mySlides");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  myIndex++;
  if (myIndex > x.length) {myIndex = 1}
  x[myIndex-1].style.display = "block";
  setTimeout(carousel, 4000);
}

// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else {
    x.className = x.className.replace(" w3-show", "");
  }
}

// When the user clicks anywhere outside of the modal, close it
var modal = document.getElementById('ticketModal');
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>
{% endblock %}
</body>

<!--end home.html>

templates/layout.html
{% load static %}
{% load auth_extras %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}CDAP{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block style %}{% endblock %}

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
   
	<!--link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet"-->
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
    <!--link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'-->
    <!--link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'-->

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!--link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"-->
    
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    
    
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">CDAP</a>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'UserManagement:search' %}">Search</a>
            </li>
            {% if not user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'UserManagement:sign_up' %}">Sign Up</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'UserManagement:sign_in' %}">Sign In</a>
            </li>
            {% endif %}
            {% if user|has_group:"crowd_user" %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'UserManagement:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'UserManagement:edit_profile' %}">Edit Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'UserManagement:change_password' %}">Change Password</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/UserManagement/MyTasks/">MyTasks</a>
            </li>

            {% endif %}
            {% if user|has_group:"admin" %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'UserManagement:profile_list' %}">View users</a>
            </li>
            <!--li class="nav-item">
                <a class="nav-link" href="{% url 'UserManagement:profile_list' %}">View tasks</a>
            </li-->
            {% endif %}

            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'UserManagement:sign_out' %}">Sign Out</a>
            </li>
            {% endif %}
            </ul>
  </div>
</nav>
<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li> {{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</div>
</body>
</html>

templates/nav.html
{% load static %}
{% load auth_extras %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">

    <title>{% block title %}CDAP{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

	<link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript" src="{% static 'js/autogrow.js' %}"> </script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"> </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>

    {% block style %} 
        <style>
            /* Navbar container */
.navbar {
  overflow: hidden;
  background-color: #333;
  font-family: Arial;
}

/* Links inside the navbar */
.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

/* The dropdown container */
.dropdown {
  float: left;
  overflow: hidden;
}

/* Dropdown button */
.dropdown .dropbtn {
  font-size: 16px;
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit; /* Important for vertical align on mobile phones */
  margin: 0; /* Important for vertical align on mobile phones */
}

/* Add a red background color to navbar links on hover */
.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

/* Dropdown content (hidden by default) */
.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

/* Links inside the dropdown */
.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

/* Add a grey background color to dropdown links on hover */
.dropdown-content a:hover {
  background-color: #ddd;
}

/* Show the dropdown menu on hover */
.dropdown:hover .dropdown-content {
  display: block;
}
        </style>
    {% endblock %}
</head>

<body>
    <div class="navbar">
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'UserManagement:search' %">Search</a>
        {% if not user.is_authenticated %}
        <a href="{% url 'UserManagement:sign_up' %}"> Sign up</a>
        <a href="{% url 'UserManagement:sign_in' %}"> Sign in</a>
        {% endif %}
        {% if user|has_group:"crowd_user" %}
        <a href="{% url 'UserManagement:profile' %}"> Profile</a>
        <div class="dropdown">
            <button class="dropbtn">Settings
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'UserManagement:change_password' %}">Change Password</a>
              <a href="{% url 'UserManagement:edit_profile' %}">Edit Profile</a>
              <a href="{% url 'UserManagement:sign_out' %}">Sign out</a>
            </div>
          </div>
        {% endif %}
        <div class="dropdown">
          <button class="dropbtn">Dropdown
            <i class="fa fa-caret-down"></i>
          </button>
          <div class="dropdown-content">
            <a href="#">Link 1</a>
            <a href="#">Link 2</a>
            <a href="#">Link 3</a>
          </div>
        </div>
      </div>
</body>